name: Publish on GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
      - name: Build site
        run: deno task build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
